### ISSUE TITLE
Where did you download your AWA data set? 

### ISSUE THREAD

**Issue by applenob** [rfelixmg/zsl_baseline#1]
The images of the AWA is currently not available on its official website. I would be very grateful if you can tell me a valid download link, or share your data set with me.

**Comment by rafafelixphd** [comment]
Hi there, indeed it's not. We didn't have access to the real images either. We just used their feature vector. It's available in their website.

Cheers,

**Comment by applenob** [comment]
OK, thank you for your reply.
